    CREATE TABLE `test` ( `uid` INT(10) NOT NULL AUTO_INCREMENT, `account_type` VARCHAR(64) NULL DEFAULT NULL, `access_key` VARCHAR(64) NULL DEFAULT NULL, `secret_key` VARCHAR(64) NULL DEFAULT NULL, PRIMARY KEY (`uid`));


